#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoffeSite.Models
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="CoffeeSite")]
	public partial class DataClasses1DataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertAbout(About instance);
    partial void UpdateAbout(About instance);
    partial void DeleteAbout(About instance);
    partial void InsertBlog(Blog instance);
    partial void UpdateBlog(Blog instance);
    partial void DeleteBlog(Blog instance);
    partial void InsertStaff(Staff instance);
    partial void UpdateStaff(Staff instance);
    partial void DeleteStaff(Staff instance);
    partial void InsertGallery(Gallery instance);
    partial void UpdateGallery(Gallery instance);
    partial void DeleteGallery(Gallery instance);
    partial void InsertContact(Contact instance);
    partial void UpdateContact(Contact instance);
    partial void DeleteContact(Contact instance);
    partial void InsertReservation(Reservation instance);
    partial void UpdateReservation(Reservation instance);
    partial void DeleteReservation(Reservation instance);
    partial void InsertInfo(Info instance);
    partial void UpdateInfo(Info instance);
    partial void DeleteInfo(Info instance);
    partial void InsertSweet(Sweet instance);
    partial void UpdateSweet(Sweet instance);
    partial void DeleteSweet(Sweet instance);
    partial void InsertCategoria(Categoria instance);
    partial void UpdateCategoria(Categoria instance);
    partial void DeleteCategoria(Categoria instance);
    partial void InsertComment(Comment instance);
    partial void UpdateComment(Comment instance);
    partial void DeleteComment(Comment instance);
    partial void InsertUserLogin(UserLogin instance);
    partial void UpdateUserLogin(UserLogin instance);
    partial void DeleteUserLogin(UserLogin instance);
    #endregion
		
		public DataClasses1DataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["CoffeeSiteConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<About> Abouts
		{
			get
			{
				return this.GetTable<About>();
			}
		}
		
		public System.Data.Linq.Table<Blog> Blogs
		{
			get
			{
				return this.GetTable<Blog>();
			}
		}
		
		public System.Data.Linq.Table<Staff> Staffs
		{
			get
			{
				return this.GetTable<Staff>();
			}
		}
		
		public System.Data.Linq.Table<Gallery> Galleries
		{
			get
			{
				return this.GetTable<Gallery>();
			}
		}
		
		public System.Data.Linq.Table<Contact> Contacts
		{
			get
			{
				return this.GetTable<Contact>();
			}
		}
		
		public System.Data.Linq.Table<Reservation> Reservations
		{
			get
			{
				return this.GetTable<Reservation>();
			}
		}
		
		public System.Data.Linq.Table<Info> Infos
		{
			get
			{
				return this.GetTable<Info>();
			}
		}
		
		public System.Data.Linq.Table<Umumi> Umumis
		{
			get
			{
				return this.GetTable<Umumi>();
			}
		}
		
		public System.Data.Linq.Table<Sweet> Sweets
		{
			get
			{
				return this.GetTable<Sweet>();
			}
		}
		
		public System.Data.Linq.Table<Categoria> Categorias
		{
			get
			{
				return this.GetTable<Categoria>();
			}
		}
		
		public System.Data.Linq.Table<Comment> Comments
		{
			get
			{
				return this.GetTable<Comment>();
			}
		}
		
		public System.Data.Linq.Table<DetailView> DetailViews
		{
			get
			{
				return this.GetTable<DetailView>();
			}
		}
		
		public System.Data.Linq.Table<UserLogin> UserLogins
		{
			get
			{
				return this.GetTable<UserLogin>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.About")]
	public partial class About : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _AboutID;
		
		private string _AboutTitle;
		
		private string _AboutContent;
		
		private string _AboutPhoto;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnAboutIDChanging(int value);
    partial void OnAboutIDChanged();
    partial void OnAboutTitleChanging(string value);
    partial void OnAboutTitleChanged();
    partial void OnAboutContentChanging(string value);
    partial void OnAboutContentChanged();
    partial void OnAboutPhotoChanging(string value);
    partial void OnAboutPhotoChanged();
    #endregion
		
		public About()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AboutID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int AboutID
		{
			get
			{
				return this._AboutID;
			}
			set
			{
				if ((this._AboutID != value))
				{
					this.OnAboutIDChanging(value);
					this.SendPropertyChanging();
					this._AboutID = value;
					this.SendPropertyChanged("AboutID");
					this.OnAboutIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AboutTitle", DbType="NVarChar(25)")]
		public string AboutTitle
		{
			get
			{
				return this._AboutTitle;
			}
			set
			{
				if ((this._AboutTitle != value))
				{
					this.OnAboutTitleChanging(value);
					this.SendPropertyChanging();
					this._AboutTitle = value;
					this.SendPropertyChanged("AboutTitle");
					this.OnAboutTitleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AboutContent", DbType="NVarChar(MAX)")]
		public string AboutContent
		{
			get
			{
				return this._AboutContent;
			}
			set
			{
				if ((this._AboutContent != value))
				{
					this.OnAboutContentChanging(value);
					this.SendPropertyChanging();
					this._AboutContent = value;
					this.SendPropertyChanged("AboutContent");
					this.OnAboutContentChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AboutPhoto", DbType="NVarChar(MAX)")]
		public string AboutPhoto
		{
			get
			{
				return this._AboutPhoto;
			}
			set
			{
				if ((this._AboutPhoto != value))
				{
					this.OnAboutPhotoChanging(value);
					this.SendPropertyChanging();
					this._AboutPhoto = value;
					this.SendPropertyChanged("AboutPhoto");
					this.OnAboutPhotoChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Blogs")]
	public partial class Blog : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _BlogsID;
		
		private string _BlogsTitle;
		
		private string _BlogsMain;
		
		private System.Nullable<System.DateTime> _BlogsDate;
		
		private string _BlogsContent;
		
		private string _BlogsPhoto;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnBlogsIDChanging(int value);
    partial void OnBlogsIDChanged();
    partial void OnBlogsTitleChanging(string value);
    partial void OnBlogsTitleChanged();
    partial void OnBlogsMainChanging(string value);
    partial void OnBlogsMainChanged();
    partial void OnBlogsDateChanging(System.Nullable<System.DateTime> value);
    partial void OnBlogsDateChanged();
    partial void OnBlogsContentChanging(string value);
    partial void OnBlogsContentChanged();
    partial void OnBlogsPhotoChanging(string value);
    partial void OnBlogsPhotoChanged();
    #endregion
		
		public Blog()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BlogsID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int BlogsID
		{
			get
			{
				return this._BlogsID;
			}
			set
			{
				if ((this._BlogsID != value))
				{
					this.OnBlogsIDChanging(value);
					this.SendPropertyChanging();
					this._BlogsID = value;
					this.SendPropertyChanged("BlogsID");
					this.OnBlogsIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BlogsTitle", DbType="NVarChar(30)")]
		public string BlogsTitle
		{
			get
			{
				return this._BlogsTitle;
			}
			set
			{
				if ((this._BlogsTitle != value))
				{
					this.OnBlogsTitleChanging(value);
					this.SendPropertyChanging();
					this._BlogsTitle = value;
					this.SendPropertyChanged("BlogsTitle");
					this.OnBlogsTitleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BlogsMain", DbType="NVarChar(MAX)")]
		public string BlogsMain
		{
			get
			{
				return this._BlogsMain;
			}
			set
			{
				if ((this._BlogsMain != value))
				{
					this.OnBlogsMainChanging(value);
					this.SendPropertyChanging();
					this._BlogsMain = value;
					this.SendPropertyChanged("BlogsMain");
					this.OnBlogsMainChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BlogsDate", DbType="Date")]
		public System.Nullable<System.DateTime> BlogsDate
		{
			get
			{
				return this._BlogsDate;
			}
			set
			{
				if ((this._BlogsDate != value))
				{
					this.OnBlogsDateChanging(value);
					this.SendPropertyChanging();
					this._BlogsDate = value;
					this.SendPropertyChanged("BlogsDate");
					this.OnBlogsDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BlogsContent", DbType="NVarChar(MAX)")]
		public string BlogsContent
		{
			get
			{
				return this._BlogsContent;
			}
			set
			{
				if ((this._BlogsContent != value))
				{
					this.OnBlogsContentChanging(value);
					this.SendPropertyChanging();
					this._BlogsContent = value;
					this.SendPropertyChanged("BlogsContent");
					this.OnBlogsContentChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BlogsPhoto", DbType="NVarChar(MAX)")]
		public string BlogsPhoto
		{
			get
			{
				return this._BlogsPhoto;
			}
			set
			{
				if ((this._BlogsPhoto != value))
				{
					this.OnBlogsPhotoChanging(value);
					this.SendPropertyChanging();
					this._BlogsPhoto = value;
					this.SendPropertyChanged("BlogsPhoto");
					this.OnBlogsPhotoChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Staff")]
	public partial class Staff : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _StaffID;
		
		private string _StaffName;
		
		private string _StaffJob;
		
		private string _StaffPhoto;
		
		private string _StaffFacebook;
		
		private string _StaffInstagram;
		
		private string _StaffLinkedin;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnStaffIDChanging(int value);
    partial void OnStaffIDChanged();
    partial void OnStaffNameChanging(string value);
    partial void OnStaffNameChanged();
    partial void OnStaffJobChanging(string value);
    partial void OnStaffJobChanged();
    partial void OnStaffPhotoChanging(string value);
    partial void OnStaffPhotoChanged();
    partial void OnStaffFacebookChanging(string value);
    partial void OnStaffFacebookChanged();
    partial void OnStaffInstagramChanging(string value);
    partial void OnStaffInstagramChanged();
    partial void OnStaffLinkedinChanging(string value);
    partial void OnStaffLinkedinChanged();
    #endregion
		
		public Staff()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StaffID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int StaffID
		{
			get
			{
				return this._StaffID;
			}
			set
			{
				if ((this._StaffID != value))
				{
					this.OnStaffIDChanging(value);
					this.SendPropertyChanging();
					this._StaffID = value;
					this.SendPropertyChanged("StaffID");
					this.OnStaffIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StaffName", DbType="NVarChar(40)")]
		public string StaffName
		{
			get
			{
				return this._StaffName;
			}
			set
			{
				if ((this._StaffName != value))
				{
					this.OnStaffNameChanging(value);
					this.SendPropertyChanging();
					this._StaffName = value;
					this.SendPropertyChanged("StaffName");
					this.OnStaffNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StaffJob", DbType="NVarChar(30)")]
		public string StaffJob
		{
			get
			{
				return this._StaffJob;
			}
			set
			{
				if ((this._StaffJob != value))
				{
					this.OnStaffJobChanging(value);
					this.SendPropertyChanging();
					this._StaffJob = value;
					this.SendPropertyChanged("StaffJob");
					this.OnStaffJobChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StaffPhoto", DbType="NVarChar(MAX)")]
		public string StaffPhoto
		{
			get
			{
				return this._StaffPhoto;
			}
			set
			{
				if ((this._StaffPhoto != value))
				{
					this.OnStaffPhotoChanging(value);
					this.SendPropertyChanging();
					this._StaffPhoto = value;
					this.SendPropertyChanged("StaffPhoto");
					this.OnStaffPhotoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StaffFacebook", DbType="NVarChar(40)")]
		public string StaffFacebook
		{
			get
			{
				return this._StaffFacebook;
			}
			set
			{
				if ((this._StaffFacebook != value))
				{
					this.OnStaffFacebookChanging(value);
					this.SendPropertyChanging();
					this._StaffFacebook = value;
					this.SendPropertyChanged("StaffFacebook");
					this.OnStaffFacebookChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StaffInstagram", DbType="NVarChar(40)")]
		public string StaffInstagram
		{
			get
			{
				return this._StaffInstagram;
			}
			set
			{
				if ((this._StaffInstagram != value))
				{
					this.OnStaffInstagramChanging(value);
					this.SendPropertyChanging();
					this._StaffInstagram = value;
					this.SendPropertyChanged("StaffInstagram");
					this.OnStaffInstagramChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StaffLinkedin", DbType="NVarChar(40)")]
		public string StaffLinkedin
		{
			get
			{
				return this._StaffLinkedin;
			}
			set
			{
				if ((this._StaffLinkedin != value))
				{
					this.OnStaffLinkedinChanging(value);
					this.SendPropertyChanging();
					this._StaffLinkedin = value;
					this.SendPropertyChanged("StaffLinkedin");
					this.OnStaffLinkedinChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Gallery")]
	public partial class Gallery : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _GalleryID;
		
		private string _GalleryPhoto;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnGalleryIDChanging(int value);
    partial void OnGalleryIDChanged();
    partial void OnGalleryPhotoChanging(string value);
    partial void OnGalleryPhotoChanged();
    #endregion
		
		public Gallery()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GalleryID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int GalleryID
		{
			get
			{
				return this._GalleryID;
			}
			set
			{
				if ((this._GalleryID != value))
				{
					this.OnGalleryIDChanging(value);
					this.SendPropertyChanging();
					this._GalleryID = value;
					this.SendPropertyChanged("GalleryID");
					this.OnGalleryIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GalleryPhoto", DbType="NVarChar(MAX)")]
		public string GalleryPhoto
		{
			get
			{
				return this._GalleryPhoto;
			}
			set
			{
				if ((this._GalleryPhoto != value))
				{
					this.OnGalleryPhotoChanging(value);
					this.SendPropertyChanging();
					this._GalleryPhoto = value;
					this.SendPropertyChanged("GalleryPhoto");
					this.OnGalleryPhotoChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Contact")]
	public partial class Contact : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ContactID;
		
		private string _ContactName;
		
		private string _ContactEmail;
		
		private string _ContactMessage;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnContactIDChanging(int value);
    partial void OnContactIDChanged();
    partial void OnContactNameChanging(string value);
    partial void OnContactNameChanged();
    partial void OnContactEmailChanging(string value);
    partial void OnContactEmailChanged();
    partial void OnContactMessageChanging(string value);
    partial void OnContactMessageChanged();
    #endregion
		
		public Contact()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ContactID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ContactID
		{
			get
			{
				return this._ContactID;
			}
			set
			{
				if ((this._ContactID != value))
				{
					this.OnContactIDChanging(value);
					this.SendPropertyChanging();
					this._ContactID = value;
					this.SendPropertyChanged("ContactID");
					this.OnContactIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ContactName", DbType="NVarChar(30)")]
		public string ContactName
		{
			get
			{
				return this._ContactName;
			}
			set
			{
				if ((this._ContactName != value))
				{
					this.OnContactNameChanging(value);
					this.SendPropertyChanging();
					this._ContactName = value;
					this.SendPropertyChanged("ContactName");
					this.OnContactNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ContactEmail", DbType="NVarChar(40)")]
		public string ContactEmail
		{
			get
			{
				return this._ContactEmail;
			}
			set
			{
				if ((this._ContactEmail != value))
				{
					this.OnContactEmailChanging(value);
					this.SendPropertyChanging();
					this._ContactEmail = value;
					this.SendPropertyChanged("ContactEmail");
					this.OnContactEmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ContactMessage", DbType="NVarChar(500)")]
		public string ContactMessage
		{
			get
			{
				return this._ContactMessage;
			}
			set
			{
				if ((this._ContactMessage != value))
				{
					this.OnContactMessageChanging(value);
					this.SendPropertyChanging();
					this._ContactMessage = value;
					this.SendPropertyChanged("ContactMessage");
					this.OnContactMessageChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Reservation")]
	public partial class Reservation : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _RsrvtnID;
		
		private string _RsrvtnName;
		
		private string _RsrvtnPhone;
		
		private System.Nullable<System.DateTime> _RsrvtnDate;
		
		private string _RsrvtnTime;
		
		private string _RsrvtnMessage;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnRsrvtnIDChanging(int value);
    partial void OnRsrvtnIDChanged();
    partial void OnRsrvtnNameChanging(string value);
    partial void OnRsrvtnNameChanged();
    partial void OnRsrvtnPhoneChanging(string value);
    partial void OnRsrvtnPhoneChanged();
    partial void OnRsrvtnDateChanging(System.Nullable<System.DateTime> value);
    partial void OnRsrvtnDateChanged();
    partial void OnRsrvtnTimeChanging(string value);
    partial void OnRsrvtnTimeChanged();
    partial void OnRsrvtnMessageChanging(string value);
    partial void OnRsrvtnMessageChanged();
    #endregion
		
		public Reservation()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RsrvtnID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int RsrvtnID
		{
			get
			{
				return this._RsrvtnID;
			}
			set
			{
				if ((this._RsrvtnID != value))
				{
					this.OnRsrvtnIDChanging(value);
					this.SendPropertyChanging();
					this._RsrvtnID = value;
					this.SendPropertyChanged("RsrvtnID");
					this.OnRsrvtnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RsrvtnName", DbType="NVarChar(40)")]
		public string RsrvtnName
		{
			get
			{
				return this._RsrvtnName;
			}
			set
			{
				if ((this._RsrvtnName != value))
				{
					this.OnRsrvtnNameChanging(value);
					this.SendPropertyChanging();
					this._RsrvtnName = value;
					this.SendPropertyChanged("RsrvtnName");
					this.OnRsrvtnNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RsrvtnPhone", DbType="NVarChar(20)")]
		public string RsrvtnPhone
		{
			get
			{
				return this._RsrvtnPhone;
			}
			set
			{
				if ((this._RsrvtnPhone != value))
				{
					this.OnRsrvtnPhoneChanging(value);
					this.SendPropertyChanging();
					this._RsrvtnPhone = value;
					this.SendPropertyChanged("RsrvtnPhone");
					this.OnRsrvtnPhoneChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RsrvtnDate", DbType="Date")]
		public System.Nullable<System.DateTime> RsrvtnDate
		{
			get
			{
				return this._RsrvtnDate;
			}
			set
			{
				if ((this._RsrvtnDate != value))
				{
					this.OnRsrvtnDateChanging(value);
					this.SendPropertyChanging();
					this._RsrvtnDate = value;
					this.SendPropertyChanged("RsrvtnDate");
					this.OnRsrvtnDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RsrvtnTime", DbType="NVarChar(20)")]
		public string RsrvtnTime
		{
			get
			{
				return this._RsrvtnTime;
			}
			set
			{
				if ((this._RsrvtnTime != value))
				{
					this.OnRsrvtnTimeChanging(value);
					this.SendPropertyChanging();
					this._RsrvtnTime = value;
					this.SendPropertyChanged("RsrvtnTime");
					this.OnRsrvtnTimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RsrvtnMessage", DbType="NVarChar(500)")]
		public string RsrvtnMessage
		{
			get
			{
				return this._RsrvtnMessage;
			}
			set
			{
				if ((this._RsrvtnMessage != value))
				{
					this.OnRsrvtnMessageChanging(value);
					this.SendPropertyChanging();
					this._RsrvtnMessage = value;
					this.SendPropertyChanged("RsrvtnMessage");
					this.OnRsrvtnMessageChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Info")]
	public partial class Info : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _InfoID;
		
		private string _InfoPlace;
		
		private string _InfoPhone;
		
		private string _InfoEmail;
		
		private string _InfoFacebook;
		
		private string _InfoInstagram;
		
		private string _InfoWhatsapp;
		
		private string _InfoOpenHours1;
		
		private string _InfoOpenHours2;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnInfoIDChanging(int value);
    partial void OnInfoIDChanged();
    partial void OnInfoPlaceChanging(string value);
    partial void OnInfoPlaceChanged();
    partial void OnInfoPhoneChanging(string value);
    partial void OnInfoPhoneChanged();
    partial void OnInfoEmailChanging(string value);
    partial void OnInfoEmailChanged();
    partial void OnInfoFacebookChanging(string value);
    partial void OnInfoFacebookChanged();
    partial void OnInfoInstagramChanging(string value);
    partial void OnInfoInstagramChanged();
    partial void OnInfoWhatsappChanging(string value);
    partial void OnInfoWhatsappChanged();
    partial void OnInfoOpenHours1Changing(string value);
    partial void OnInfoOpenHours1Changed();
    partial void OnInfoOpenHours2Changing(string value);
    partial void OnInfoOpenHours2Changed();
    #endregion
		
		public Info()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_InfoID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int InfoID
		{
			get
			{
				return this._InfoID;
			}
			set
			{
				if ((this._InfoID != value))
				{
					this.OnInfoIDChanging(value);
					this.SendPropertyChanging();
					this._InfoID = value;
					this.SendPropertyChanged("InfoID");
					this.OnInfoIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_InfoPlace", DbType="NVarChar(100)")]
		public string InfoPlace
		{
			get
			{
				return this._InfoPlace;
			}
			set
			{
				if ((this._InfoPlace != value))
				{
					this.OnInfoPlaceChanging(value);
					this.SendPropertyChanging();
					this._InfoPlace = value;
					this.SendPropertyChanged("InfoPlace");
					this.OnInfoPlaceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_InfoPhone", DbType="NVarChar(20)")]
		public string InfoPhone
		{
			get
			{
				return this._InfoPhone;
			}
			set
			{
				if ((this._InfoPhone != value))
				{
					this.OnInfoPhoneChanging(value);
					this.SendPropertyChanging();
					this._InfoPhone = value;
					this.SendPropertyChanged("InfoPhone");
					this.OnInfoPhoneChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_InfoEmail", DbType="NVarChar(40)")]
		public string InfoEmail
		{
			get
			{
				return this._InfoEmail;
			}
			set
			{
				if ((this._InfoEmail != value))
				{
					this.OnInfoEmailChanging(value);
					this.SendPropertyChanging();
					this._InfoEmail = value;
					this.SendPropertyChanged("InfoEmail");
					this.OnInfoEmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_InfoFacebook", DbType="NVarChar(100)")]
		public string InfoFacebook
		{
			get
			{
				return this._InfoFacebook;
			}
			set
			{
				if ((this._InfoFacebook != value))
				{
					this.OnInfoFacebookChanging(value);
					this.SendPropertyChanging();
					this._InfoFacebook = value;
					this.SendPropertyChanged("InfoFacebook");
					this.OnInfoFacebookChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_InfoInstagram", DbType="NVarChar(100)")]
		public string InfoInstagram
		{
			get
			{
				return this._InfoInstagram;
			}
			set
			{
				if ((this._InfoInstagram != value))
				{
					this.OnInfoInstagramChanging(value);
					this.SendPropertyChanging();
					this._InfoInstagram = value;
					this.SendPropertyChanged("InfoInstagram");
					this.OnInfoInstagramChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_InfoWhatsapp", DbType="NVarChar(100)")]
		public string InfoWhatsapp
		{
			get
			{
				return this._InfoWhatsapp;
			}
			set
			{
				if ((this._InfoWhatsapp != value))
				{
					this.OnInfoWhatsappChanging(value);
					this.SendPropertyChanging();
					this._InfoWhatsapp = value;
					this.SendPropertyChanged("InfoWhatsapp");
					this.OnInfoWhatsappChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_InfoOpenHours1", DbType="NVarChar(100)")]
		public string InfoOpenHours1
		{
			get
			{
				return this._InfoOpenHours1;
			}
			set
			{
				if ((this._InfoOpenHours1 != value))
				{
					this.OnInfoOpenHours1Changing(value);
					this.SendPropertyChanging();
					this._InfoOpenHours1 = value;
					this.SendPropertyChanged("InfoOpenHours1");
					this.OnInfoOpenHours1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_InfoOpenHours2", DbType="NVarChar(100)")]
		public string InfoOpenHours2
		{
			get
			{
				return this._InfoOpenHours2;
			}
			set
			{
				if ((this._InfoOpenHours2 != value))
				{
					this.OnInfoOpenHours2Changing(value);
					this.SendPropertyChanging();
					this._InfoOpenHours2 = value;
					this.SendPropertyChanged("InfoOpenHours2");
					this.OnInfoOpenHours2Changed();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Umumi")]
	public partial class Umumi
	{
		
		private int _SweetsId;
		
		private string _SweetsName;
		
		private string _SweetsContent;
		
		private string _SweetsPrice;
		
		private string _SweetsPhoto;
		
		private System.Nullable<int> _SweetsCategoriaId;
		
		private System.Nullable<int> _CategoriaId;
		
		private string _CategoriaName;
		
		public Umumi()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SweetsId", DbType="Int NOT NULL")]
		public int SweetsId
		{
			get
			{
				return this._SweetsId;
			}
			set
			{
				if ((this._SweetsId != value))
				{
					this._SweetsId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SweetsName", DbType="NVarChar(25)")]
		public string SweetsName
		{
			get
			{
				return this._SweetsName;
			}
			set
			{
				if ((this._SweetsName != value))
				{
					this._SweetsName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SweetsContent", DbType="NVarChar(MAX)")]
		public string SweetsContent
		{
			get
			{
				return this._SweetsContent;
			}
			set
			{
				if ((this._SweetsContent != value))
				{
					this._SweetsContent = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SweetsPrice", DbType="NVarChar(10)")]
		public string SweetsPrice
		{
			get
			{
				return this._SweetsPrice;
			}
			set
			{
				if ((this._SweetsPrice != value))
				{
					this._SweetsPrice = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SweetsPhoto", DbType="NVarChar(MAX)")]
		public string SweetsPhoto
		{
			get
			{
				return this._SweetsPhoto;
			}
			set
			{
				if ((this._SweetsPhoto != value))
				{
					this._SweetsPhoto = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SweetsCategoriaId", DbType="Int")]
		public System.Nullable<int> SweetsCategoriaId
		{
			get
			{
				return this._SweetsCategoriaId;
			}
			set
			{
				if ((this._SweetsCategoriaId != value))
				{
					this._SweetsCategoriaId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CategoriaId", DbType="Int")]
		public System.Nullable<int> CategoriaId
		{
			get
			{
				return this._CategoriaId;
			}
			set
			{
				if ((this._CategoriaId != value))
				{
					this._CategoriaId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CategoriaName", DbType="NVarChar(25)")]
		public string CategoriaName
		{
			get
			{
				return this._CategoriaName;
			}
			set
			{
				if ((this._CategoriaName != value))
				{
					this._CategoriaName = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Sweets")]
	public partial class Sweet : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _SweetsId;
		
		private string _SweetsName;
		
		private string _SweetsContent;
		
		private string _SweetsPrice;
		
		private string _SweetsPhoto;
		
		private System.Nullable<int> _SweetsCategoriaId;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnSweetsIdChanging(int value);
    partial void OnSweetsIdChanged();
    partial void OnSweetsNameChanging(string value);
    partial void OnSweetsNameChanged();
    partial void OnSweetsContentChanging(string value);
    partial void OnSweetsContentChanged();
    partial void OnSweetsPriceChanging(string value);
    partial void OnSweetsPriceChanged();
    partial void OnSweetsPhotoChanging(string value);
    partial void OnSweetsPhotoChanged();
    partial void OnSweetsCategoriaIdChanging(System.Nullable<int> value);
    partial void OnSweetsCategoriaIdChanged();
    #endregion
		
		public Sweet()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SweetsId", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int SweetsId
		{
			get
			{
				return this._SweetsId;
			}
			set
			{
				if ((this._SweetsId != value))
				{
					this.OnSweetsIdChanging(value);
					this.SendPropertyChanging();
					this._SweetsId = value;
					this.SendPropertyChanged("SweetsId");
					this.OnSweetsIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SweetsName", DbType="NVarChar(25)")]
		public string SweetsName
		{
			get
			{
				return this._SweetsName;
			}
			set
			{
				if ((this._SweetsName != value))
				{
					this.OnSweetsNameChanging(value);
					this.SendPropertyChanging();
					this._SweetsName = value;
					this.SendPropertyChanged("SweetsName");
					this.OnSweetsNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SweetsContent", DbType="NVarChar(MAX)")]
		public string SweetsContent
		{
			get
			{
				return this._SweetsContent;
			}
			set
			{
				if ((this._SweetsContent != value))
				{
					this.OnSweetsContentChanging(value);
					this.SendPropertyChanging();
					this._SweetsContent = value;
					this.SendPropertyChanged("SweetsContent");
					this.OnSweetsContentChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SweetsPrice", DbType="NVarChar(10)")]
		public string SweetsPrice
		{
			get
			{
				return this._SweetsPrice;
			}
			set
			{
				if ((this._SweetsPrice != value))
				{
					this.OnSweetsPriceChanging(value);
					this.SendPropertyChanging();
					this._SweetsPrice = value;
					this.SendPropertyChanged("SweetsPrice");
					this.OnSweetsPriceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SweetsPhoto", DbType="NVarChar(MAX)")]
		public string SweetsPhoto
		{
			get
			{
				return this._SweetsPhoto;
			}
			set
			{
				if ((this._SweetsPhoto != value))
				{
					this.OnSweetsPhotoChanging(value);
					this.SendPropertyChanging();
					this._SweetsPhoto = value;
					this.SendPropertyChanged("SweetsPhoto");
					this.OnSweetsPhotoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SweetsCategoriaId", DbType="Int")]
		public System.Nullable<int> SweetsCategoriaId
		{
			get
			{
				return this._SweetsCategoriaId;
			}
			set
			{
				if ((this._SweetsCategoriaId != value))
				{
					this.OnSweetsCategoriaIdChanging(value);
					this.SendPropertyChanging();
					this._SweetsCategoriaId = value;
					this.SendPropertyChanged("SweetsCategoriaId");
					this.OnSweetsCategoriaIdChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Categoria")]
	public partial class Categoria : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _CategoriaId;
		
		private string _CategoriaName;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCategoriaIdChanging(int value);
    partial void OnCategoriaIdChanged();
    partial void OnCategoriaNameChanging(string value);
    partial void OnCategoriaNameChanged();
    #endregion
		
		public Categoria()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CategoriaId", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int CategoriaId
		{
			get
			{
				return this._CategoriaId;
			}
			set
			{
				if ((this._CategoriaId != value))
				{
					this.OnCategoriaIdChanging(value);
					this.SendPropertyChanging();
					this._CategoriaId = value;
					this.SendPropertyChanged("CategoriaId");
					this.OnCategoriaIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CategoriaName", DbType="NVarChar(25)")]
		public string CategoriaName
		{
			get
			{
				return this._CategoriaName;
			}
			set
			{
				if ((this._CategoriaName != value))
				{
					this.OnCategoriaNameChanging(value);
					this.SendPropertyChanging();
					this._CategoriaName = value;
					this.SendPropertyChanged("CategoriaName");
					this.OnCategoriaNameChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Comment")]
	public partial class Comment : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _CommentID;
		
		private string _CommentName;
		
		private string _CommentEmail;
		
		private string _CommentMessage;
		
		private System.Nullable<int> _CommentBlogsId;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCommentIDChanging(int value);
    partial void OnCommentIDChanged();
    partial void OnCommentNameChanging(string value);
    partial void OnCommentNameChanged();
    partial void OnCommentEmailChanging(string value);
    partial void OnCommentEmailChanged();
    partial void OnCommentMessageChanging(string value);
    partial void OnCommentMessageChanged();
    partial void OnCommentBlogsIdChanging(System.Nullable<int> value);
    partial void OnCommentBlogsIdChanged();
    #endregion
		
		public Comment()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CommentID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int CommentID
		{
			get
			{
				return this._CommentID;
			}
			set
			{
				if ((this._CommentID != value))
				{
					this.OnCommentIDChanging(value);
					this.SendPropertyChanging();
					this._CommentID = value;
					this.SendPropertyChanged("CommentID");
					this.OnCommentIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CommentName", DbType="NVarChar(30)")]
		public string CommentName
		{
			get
			{
				return this._CommentName;
			}
			set
			{
				if ((this._CommentName != value))
				{
					this.OnCommentNameChanging(value);
					this.SendPropertyChanging();
					this._CommentName = value;
					this.SendPropertyChanged("CommentName");
					this.OnCommentNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CommentEmail", DbType="NVarChar(40)")]
		public string CommentEmail
		{
			get
			{
				return this._CommentEmail;
			}
			set
			{
				if ((this._CommentEmail != value))
				{
					this.OnCommentEmailChanging(value);
					this.SendPropertyChanging();
					this._CommentEmail = value;
					this.SendPropertyChanged("CommentEmail");
					this.OnCommentEmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CommentMessage", DbType="NVarChar(500)")]
		public string CommentMessage
		{
			get
			{
				return this._CommentMessage;
			}
			set
			{
				if ((this._CommentMessage != value))
				{
					this.OnCommentMessageChanging(value);
					this.SendPropertyChanging();
					this._CommentMessage = value;
					this.SendPropertyChanged("CommentMessage");
					this.OnCommentMessageChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CommentBlogsId", DbType="Int")]
		public System.Nullable<int> CommentBlogsId
		{
			get
			{
				return this._CommentBlogsId;
			}
			set
			{
				if ((this._CommentBlogsId != value))
				{
					this.OnCommentBlogsIdChanging(value);
					this.SendPropertyChanging();
					this._CommentBlogsId = value;
					this.SendPropertyChanged("CommentBlogsId");
					this.OnCommentBlogsIdChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.DetailView")]
	public partial class DetailView
	{
		
		private int _BlogsID;
		
		private string _BlogsTitle;
		
		private string _BlogsMain;
		
		private System.Nullable<System.DateTime> _BlogsDate;
		
		private string _BlogsContent;
		
		private string _BlogsPhoto;
		
		private System.Nullable<int> _CommentID;
		
		private string _CommentName;
		
		private string _CommentEmail;
		
		private string _CommentMessage;
		
		private System.Nullable<int> _CommentBlogsId;
		
		public DetailView()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BlogsID", DbType="Int NOT NULL")]
		public int BlogsID
		{
			get
			{
				return this._BlogsID;
			}
			set
			{
				if ((this._BlogsID != value))
				{
					this._BlogsID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BlogsTitle", DbType="NVarChar(30)")]
		public string BlogsTitle
		{
			get
			{
				return this._BlogsTitle;
			}
			set
			{
				if ((this._BlogsTitle != value))
				{
					this._BlogsTitle = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BlogsMain", DbType="NVarChar(MAX)")]
		public string BlogsMain
		{
			get
			{
				return this._BlogsMain;
			}
			set
			{
				if ((this._BlogsMain != value))
				{
					this._BlogsMain = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BlogsDate", DbType="Date")]
		public System.Nullable<System.DateTime> BlogsDate
		{
			get
			{
				return this._BlogsDate;
			}
			set
			{
				if ((this._BlogsDate != value))
				{
					this._BlogsDate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BlogsContent", DbType="NVarChar(MAX)")]
		public string BlogsContent
		{
			get
			{
				return this._BlogsContent;
			}
			set
			{
				if ((this._BlogsContent != value))
				{
					this._BlogsContent = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BlogsPhoto", DbType="NVarChar(MAX)")]
		public string BlogsPhoto
		{
			get
			{
				return this._BlogsPhoto;
			}
			set
			{
				if ((this._BlogsPhoto != value))
				{
					this._BlogsPhoto = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CommentID", DbType="Int")]
		public System.Nullable<int> CommentID
		{
			get
			{
				return this._CommentID;
			}
			set
			{
				if ((this._CommentID != value))
				{
					this._CommentID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CommentName", DbType="NVarChar(30)")]
		public string CommentName
		{
			get
			{
				return this._CommentName;
			}
			set
			{
				if ((this._CommentName != value))
				{
					this._CommentName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CommentEmail", DbType="NVarChar(40)")]
		public string CommentEmail
		{
			get
			{
				return this._CommentEmail;
			}
			set
			{
				if ((this._CommentEmail != value))
				{
					this._CommentEmail = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CommentMessage", DbType="NVarChar(500)")]
		public string CommentMessage
		{
			get
			{
				return this._CommentMessage;
			}
			set
			{
				if ((this._CommentMessage != value))
				{
					this._CommentMessage = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CommentBlogsId", DbType="Int")]
		public System.Nullable<int> CommentBlogsId
		{
			get
			{
				return this._CommentBlogsId;
			}
			set
			{
				if ((this._CommentBlogsId != value))
				{
					this._CommentBlogsId = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.UserLogin")]
	public partial class UserLogin : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _UserLoginId;
		
		private string _Username;
		
		private string _Userpassword;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnUserLoginIdChanging(int value);
    partial void OnUserLoginIdChanged();
    partial void OnUsernameChanging(string value);
    partial void OnUsernameChanged();
    partial void OnUserpasswordChanging(string value);
    partial void OnUserpasswordChanged();
    #endregion
		
		public UserLogin()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserLoginId", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int UserLoginId
		{
			get
			{
				return this._UserLoginId;
			}
			set
			{
				if ((this._UserLoginId != value))
				{
					this.OnUserLoginIdChanging(value);
					this.SendPropertyChanging();
					this._UserLoginId = value;
					this.SendPropertyChanged("UserLoginId");
					this.OnUserLoginIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Username", DbType="NVarChar(25)")]
		public string Username
		{
			get
			{
				return this._Username;
			}
			set
			{
				if ((this._Username != value))
				{
					this.OnUsernameChanging(value);
					this.SendPropertyChanging();
					this._Username = value;
					this.SendPropertyChanged("Username");
					this.OnUsernameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Userpassword", DbType="NVarChar(20)")]
		public string Userpassword
		{
			get
			{
				return this._Userpassword;
			}
			set
			{
				if ((this._Userpassword != value))
				{
					this.OnUserpasswordChanging(value);
					this.SendPropertyChanging();
					this._Userpassword = value;
					this.SendPropertyChanged("Userpassword");
					this.OnUserpasswordChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
